Ext.define('PSS.controller.DepartmentController',{
	add:function(datas,callback){
		Ext.Ajax.request({
			url:require('./config.json').host+'/add_department',
			method:'POST',
			params:datas,
			success:function(response,opts){
				if(callback){
					callback(JSON.parse(response.responseText));
				}
			},
			failure:function(response,opts){
				Ext.Msg.alert('添加部门','网络错误');
			}
		});
	},
	remove:function(datas,callback){
		Ext.Ajax.request({
			url:require('./config.json').host + '/remove_department',
			method:'POST',
			params:datas,
			success:function(response,opts){
				if(callback){
					callback(JSON.parse(response.responseText));
				}
			},
			failure:function(response,opts){
				Ext.Msg.alert('删除部门','网络错误');
			}
		});
	},
	update:function(datas,callback){
		Ext.Ajax.request({
			url:require('./config.json').host+'/update_department',
			method:'POST',
			params:datas,
			success:function(response,opts){
				if(callback){
					callback(JSON.parse(response.responseText));
				}
			},
			failure:function(response,opts){
				Ext.Msg.alert('更新部门','网络错误');
			}
		});
	}
})