# -*-coding:utf-8 -*-
# 常量

class Constants():
    REGISTER_SUCCESS = 0
    REGSISTER_FAILED = -1
    NAME_EXISTED = -2
    INVALID_ARGS = -3
    BARCODE_EXISTED = -4
    PROP_VALUE_EXISTED = -5

    # 商品属性类型
    PRODUCT_PROP_TYPE_SKU = 1
    PRODUCT_PROP_TYPE_INT = 2
    PRODUCT_PROP_TYPE_FLOAT = 3
    PRODUCT_PROP_TYPE_STRING = 4
    PRODUCT_PROP_TYPE_DATE = 5